version: "3.8"
services:
  redis:
    image: "redis:7.0"
    container_name: "redis"
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf